
drop table if exists public.tkr_group;
drop table if exists public.tkr_data;
drop table if exists public.tkr_delivery; -- public.trk_entrega;
drop table if exists public.adm_tanker_driver;
drop table if exists public.adm_gas_station;
drop table if exists public.adm_tanker; -- adm_tanker
drop table if exists public.adm_driver;
drop table if exists public.adm_company; -- adm_empersa

CREATE TABLE if not exists public.adm_company (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name_ VARCHAR(200) NOT NULL,
    nit VARCHAR(50),
    address VARCHAR(250),
    telephone VARCHAR(50),
    email VARCHAR(150),
    wallet VARCHAR(150) NOT NULL UNIQUE,
    hash_company VARCHAR(500),
    state VARCHAR(50) NOT NULL DEFAULT 'ACTIVA',
    created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
    constraint pk_company primary  key(id)
);

---------------------------------
CREATE TABLE if not exists public.adm_tanker(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_id bigint NOT NULL,
    plate VARCHAR(20) NOT NULL UNIQUE,
    capacity DECIMAL(10,2) NOT NULL,
    model_sensor VARCHAR(100),
    state VARCHAR(50) NOT NULL DEFAULT 'ACTIVA',
    created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
    constraint pk_tanker primary key(id),
    CONSTRAINT FK_tanker_company FOREIGN KEY (company_id)
        REFERENCES adm_company(id)
);

--------------------------

CREATE TABLE if not exists public.adm_driver (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    company_id bigINT NOT NULL,
    name_ VARCHAR(150) NOT NULL,
    licence VARCHAR(50) NOT NULL UNIQUE,
    state VARCHAR(50) NOT NULL DEFAULT 'ACTIVO',
    hash_id VARCHAR(500),
    created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
	constraint pk_driver primary key(id),
    CONSTRAINT FK_driver_company FOREIGN KEY (company_id)
        REFERENCES adm_company(id)
);
---------------------------------------
CREATE TABLE if not exists public.adm_gas_station (
    id bigint not null generated by default as identity,
    company_id bigINT NOT NULL,
    name_ VARCHAR(150) NOT NULL,
    address VARCHAR(250),
    state VARCHAR(50) NOT NULL DEFAULT 'ACTIVO',
    created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
	constraint pk_gas_station primary key(id),
    CONSTRAINT FK_gasstation_company FOREIGN KEY (company_id)
        REFERENCES adm_company(id)
);

-----------------------------------
CREATE TABLE if not exists public.adm_tanker_driver (
    id bigINT not null generated by default as identity,
    tanker_id bigINT NOT NULL,
    driver_id INT NOT NULL,
    fecha_fin timestamp null,
    created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
    constraint pk_tanker_driver primary key(id),
    CONSTRAINT FK_tankerdriver_tanker FOREIGN KEY (tanker_id)
        REFERENCES adm_tanker(id),
    CONSTRAINT FK_tankerdriver_driver FOREIGN KEY (driver_id)
        REFERENCES adm_driver(id)
);
-------------------
CREATE TABLE if not exists public.tkr_data (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tanker_id bigint NOT NULL,
	gps_coordinate point NULL,
	volume float4 NULL,
	state_motor varchar(20) NULL,
	hash_device varchar(100) NOT NULL,
	send_date date NOT NULL,
	group_blck int NOT null, 
	created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
	constraint pk_data primary  key(id)
);
---------------


CREATE TABLE if not exists public.tkr_delivery (
    id BIGINT not null generated by default as identity,
    tanker_id bigINT NOT NULL,
    gasstation_id bigINT NOT NULL,
    volume_delivery DECIMAL(10,2) NOT NULL,
    tokens_burns DECIMAL(10,2) NOT NULL,
    hash_transaction VARCHAR(500),
    created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
	constraint pk_delivery primary key(id),
    CONSTRAINT FK_delivery_tanker FOREIGN KEY (tanker_id)
        REFERENCES adm_tanker(id),
    CONSTRAINT FK_delivery_gasstation FOREIGN KEY (gasstation_id)
        REFERENCES adm_gas_station(id)
);



create table if not exists public.tkr_group(
	id bigint not null generated by default as identity,
	hash_group varchar(500) not null,
	data_id_start bigint not null,
	data_id_finish bigint not null,
	hash_blkc  varchar(1000),
	created_at TIMESTAMP not null,
	updated_at TIMESTAMP null,
	deleted_at TIMESTAMP null,
	constraint pk_group primary key(id)
);